FROM python:3.8

WORKDIR /usr/src/app

COPY . .

RUN python3 -m pip install -r requirements.txt

ENTRYPOINT ["python3"]

#https://hub.docker.com/layers/pashovp/testrepo/latest/images/sha256-c522f053171f50d042af19e452857918dae4a64f70b3584dea238b71cf53bd62?context=repo&tab=layers