version: '3.8'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  web:
    build: ./example-backend
    environment:
      - REDIS_HOST=redis
    ports:
      - '8080:8080'

  front-end:
    build: ./example-frontend
    ports:
      - '5000:5000'
